### ISSUE TITLE
Python 3.9 issue when installing

### ISSUE THREAD

**Issue by benjaminforest** [swistakm/pyimgui#183]
make build gives errors. I noticed you are specifying an old version of Cython in requirements-dev.txt (0.28.2), any reason for that ?
It seems to work when I replace `Cython>=0.24,<=0.28.2` by  `Cython>=0.24,<=0.29.21` in this file.

**Comment by Johndeep** [comment]
I want to +1 this, since in Debian (testing), python 3.9 unfortunately replaced python 3.8 already just yesterday. Now I'm not able to install imgui via pip3, seemingly because of this or some setup error.
It would be cool to at least configure the setup for imgui to be installed properly. I really like pyimgui, since it allows me to work within python3 with that powerful GUI tool.

Is there a simple workaround I can do until the update, which unfortunately seems to take it's time, considering this issue is already a month old?

**Comment by Johndeep** [comment]
Okay, I've looked around and found a workaround for those, who is willing to do some work. This works at least on Linux (did it on Debian). And this is needed, if you only have python-3.9.

1. get the pyimgui package via `git clone` onto your PC, where does not matter.
2. go into that folder
2.1. open Makefile and edit every `python` command to `python3` (because in my case, python is not recognized anymore)
2.2. goto the folder `doc` and edit all three `requirements-*.txt` files. Do it like @benjaminforest did, replace `Cython>=0.24,<=0.28.2` with `Cython>=0.24,<=0.29.21`.
3. go back into root folder `pyimgui`, open Terminal and execute `make build`, now the Makefile should do the rest (install cpython, fetch imgui, compile the packages)
4. Done, now the setup linked the newly compiled package with your pyimgui folder. So do not delete this folder as long as you're working with imgui. This is also required to uninstall the package later on, I think.

In my case, pycharm could recognized the new packages within python-3.9 immediately and everything works fine again. For now.

**Comment by swistakm** [comment]
Yeah, that Cython specifier needs some more tuning especially in regards to Python versions available. I am increasing that to `<0.30` but we will have to revisit in next major release which will drop support for EOL Python versions.

I'm closing this as it has been fixed in source so code should be installable from sources. New wheel is on the way too.

**Comment by Johndeep** [comment]
Yay, cannot wait for it :+1: then I can remove the manual installation and to pip again ^^

**Comment by swistakm** [comment]
Released as `1.3.0`:
- [release notes](https://github.com/swistakm/pyimgui/releases/tag/1.3.0)
- [available distributions](https://pypi.org/project/imgui/1.3.0/#files)
