### ISSUE TITLE
Parallel projects

### ISSUE THREAD

**Issue by jr-garcia** [swistakm/pyimgui#2]
You know, I have started hating Github's announcing style on web search engines. If I had found your project before, I wouldn't wasted my time starting my own. Check [here](https://github.com/jr-garcia/PyImGui-Lite). Maybe you can integrate the SDL2 part to increase the completion of your project, or just check it out or whatever. If you are willing to keep being the PyImgui dev, I'm just dropping my version right know (no need for two of the same). Good work and good luck!  :relaxed:  :+1:

**Comment by swistakm** [comment]
Yeah, I completely understand your pain. It was also hard for me to find any other Python package for ImGui.

Anyway, I assure you that I'm determined to finish this project and publish it on PyPI. I'm working actively on it and I try to add some code every day since I started it. I will still take some time to have 100% of feature mapping because ImGui is huge and wrapping it completely requires a lot of toilsome and repetitive work.

This is why it would be glad if someone helped me. I encourage you to contribute :)

Right now pyimgui has mapping for the most basic widgets, layout functions and style/gui-state classes. I think that priorities for now are:
* providing complete mapping of all available widgets
* providing documentation in form of "developer's guide" for:
  * most basic work-flow for immediate mode GUI (i.e. start frame, dispatch input events, define GUI elements, render frame)
  * working with style variables stack (`push_style_var()`, `pop_style_var()` etc.)
  * how to make own integration with ImGui (this will also require documenting `DrawList` and other related classes)
* providing simple GLUT integration so demo code could be started without any other platform specific imports and downloads (glfw requires specific dll for user platform). This will probably require us to extract most of existing GLWF integration to basic GL integration class (just to reuse integration code) and then provide support for GLUT inputs.

Project has not any style checks and style convention defined yet but it should be pretty consistent in its current state. Anyway, if something is not obvious I can provide more information in form of development tips and contribution guide. Just create github issue if in doubt. If you find that something should be formalised and documented just say it. I'm open for any suggestions.

Last note: project does not have any testing right now because it's is really hard to test GUI frameworks. Anyway, Sphinx is configured here in a way that allows it to render examples from function docstrings and doc sources (using custom `.. visual-example::` directive), so documentation also serves a semi-testing purpose. We can later try to measure coverage during doc builds and/or try to include some tests that check return values of functions.

**Comment by swistakm** [comment]
I forgot to add: SDL2 integration should be also in the roadmap. Its not in the "top priorities" list but if you want to contribute it first I will review it with pleasure.

Anyway everything in the `impl` sub package is still a draft and I'm still not sure how the API for it should be designed. Consider current structure of "implementation" layers as unstable API that may change and is open for discussion.
