### ISSUE TITLE
Checkbox doesn't work

### ISSUE THREAD

**Issue by LuminousLizard** [swistakm/pyimgui#87]
Greetings,

First: Thanks for the imgui wrapper :+1:  
Second: I'm working through your documentary right now to learn pyimgui, and I have a problem with the checkbox. Your example doesn't work for me:
```
imgui.begin("Example: checkboxes")

c1_output = imgui.checkbox("Checkbox 1", True)
c2_output = imgui.checkbox("Checkbox 2", False)

imgui.text("Checkbox 1 return value: {}".format(c1_output))
imgui.text("Checkbox 2 return value: {}".format(c2_output))

imgui.end()
``` 
The checkbox is displayed but I cannot change the state of the checkbox if I execute the script. I've tried a few other ways too, but without success. 

I use the pygame backend and the checkbox in your example script with all widgets and functions works. 

Here you can find my full source code: [https://gitlab.com/LuminousLizard/pyimgui-user-friendly/blob/master/Pyimgui_elements/13_checkbox.py](url)

**Comment by swistakm** [comment]
Hi!
The documentation of some widgets may be sometimes a bit misleading and we'll try to improve that.

The second `state` argument in `imgui.checkbox()` widget is your desired state of the checkbox. So if you "statically" pass `True` literal then your checkbox will be always rendered as checked. You need to store output state of the widget in some secondary variable and modify it on every frame when checkbox is rendered. Here is better example fo how it should be documented:

```python
# note: these should be initialized outside of the main interaction
#       loop
checkbox1_enabled = True
checkbox2_enabled = False

imgui.new_frame()
imgui.begin("Example: checkboxes")

# note: first element of return two-tuple notifies if there was a click
#       event in currently processed frame and second element is actual
#       checkbox state.
_, checkbox1_enabled = imgui.checkbox("Checkbox 1", checkbox1_enabled)
_, checkbox2_enabled = imgui.checkbox("Checkbox 2", checkbox2_enabled)

imgui.text("Checkbox 1 state value: {}".format(checkbox1_enabled))
imgui.text("Checkbox 2 state value: {}".format(checkbox2_enabled))

imgui.end()
```

Note that it is extremely important to not manually redefine values `checkbox1_enabled` and `checkbox2_enabled` on every step rendering. In official documentation it is sometimes presented that way because we process documentation automatically to generate example images.

For instance, in code using glfw3 integration this code could look like following:

```python
# this is some function that initializes glfw window context
window = impl_glfw_init()
impl = GlfwRenderer(window)

# these are widget states initialized before main "while" interaction loop 
checkbox1_enabled = True
checkbox2_enabled = False

while not glfw.window_should_close(window):
    glfw.poll_events()
    impl.process_inputs()

    imgui.new_frame()
    imgui.begin("Example: checkboxes")

    # here widget states are stored in external variables
    _, checkbox1_enabled = imgui.checkbox("Checkbox 1", checkbox1_enabled)
    _, checkbox2_enabled = imgui.checkbox("Checkbox 2", checkbox2_enabled)

    imgui.text("Checkbox 1 state value: {}".format(checkbox1_enabled))
    imgui.text("Checkbox 2 state value: {}".format(checkbox2_enabled))

    imgui.end()

    imgui.render()
    impl.render(imgui.get_draw_data())
    glfw.swap_buffers(window)

impl.shutdown()
glfw.terminate()
```

**Comment by LuminousLizard** [comment]
Thank you ... now I get it ! :+1:
