### ISSUE TITLE
events in pyimgui

### ISSUE THREAD

**Issue by KenoLeon** [swistakm/pyimgui#97]
Trying to integrate  existing pygame  code and am having issues with the event loop, could be a good addition to the docs... anyways in pygame  I'd do something like ( quit when pressing the q key):

`if event.type == KEYDOWN and event.key == K_q:
            pygame.quit()
            sys.exit() `

Not sure I follow what the [integrations](https://github.com/swistakm/pyimgui/blob/master/imgui/integrations/pygame.py) equivalent is ?

**Comment by overdev** [comment]
@swistakm can give you a better answer for this, but maybe I can help.

[This example](https://github.com/swistakm/pyimgui/blob/master/doc/examples/pygame_.py) in the docs might be a good example on how to deal with pygame events.

Note that you do this just like with any other pygame game logic, except that you call ``PygameRenderer.process_event(event)`` for each event type to allow pyimgui to update it's internal state.

**Comment by KenoLeon** [comment]
@overdev : Thanks, I've been playing with a pared down version of that one, so the event now works... turns out I was missing an import 🥇 

```
from __future__ import absolute_import
import sys
import pygame
from pygame.locals import *
import OpenGL.GL as gl
from imgui.integrations.pygame import PygameRenderer
import imgui


def main():
    pygame.init()
    # Screen Setup:
    infoObject = pygame.display.Info()
    size = infoObject.current_w, infoObject.current_h
    pygame.display.set_mode(size, pygame.DOUBLEBUF | pygame.OPENGL)

    # Imgui setup:
    io = imgui.get_io()
    io.fonts.add_font_default()
    io.display_size = size
    renderer = PygameRenderer()

    while True:
        # Events:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
            elif event.type == KEYDOWN and event.key == K_q:
                sys.exit()
            # imgui render :
            renderer.process_event(event)

        imgui.new_frame()
        imgui.begin("Example: empty window", True)
        imgui.end()

        gl.glClearColor(1, 1, 1, 1)
        gl.glClear(gl.GL_COLOR_BUFFER_BIT)
        imgui.render()

        pygame.display.flip()

if __name__ == "__main__":
    main()

```



My main question still remains though, not sure yet (started working yesterday with pyimgui) which event loop takes precedence pygame's or pyimgui or if they coexist, but maybe I am just not there yet, ( haven't gotten to bindings) and the docs so far I think could use some work in the introduction, maybe I can help later when I know more.

**Comment by swistakm** [comment]
@KenoLeon your approach (the one from last snippet) is a correct one.

Regarding the precedence of event loops. This is a interesting question because actually there is no distinction between pygame and imgui event loop. The only event loop is the one you define yourself:
```
while True:
    # Events:
    for event in pygame.event.get():
        # process your event
        ...

    # do things that you do on every frame
    ...
```

The `renderer.process_event(event)` only tracks changes of inputs (mouse, keyboard) in proper input tables of imgui and imgui decides by itself if it should display changes in the UI accordingly.

If by "precedence" you mean exclusively consuming the events by either the imgui or pygame in a way that events do not collide then you will have to define that logic by yourself. Good start would be to process your UI first (without display) and then decide if there could be any interaction in your UI. If there could be some UI interaction (e.g. any UI item hovered/active) then you simply skip processing events outside imgui. Otherwise you can handle events normally as you would in pygame (`if ... elif .. else` blocks). [Here](https://github.com/ocornut/imgui/blob/master/imgui.h#L613-L615) are some functions in ImGui that would help you determining if there coud be UI interaction. If any of these functions is missing in our bindings then we can easily add them to the library.

**Comment by swistakm** [comment]
I'm closing because I assume question is answered. I have added label to this issue so it would be easier to search or document if anuone has similar question in future.
